import pandas as pd
import plotly.express as px



def display_scatter_plot(y_axis: str) -> None:
    
    #Read the CSV generated by C++
    if(y_axis.lower() == "x"): 
        df = pd.read_csv("logging/dataRotX.csv") 
    else:
        df = pd.read_csv("logging/dataRotY.csv")

    #Create an interactive scatter plot
    fig = px.scatter(df, x="t", y=f"rot{y_axis.upper()}", title=f"Simulation Data: t(s) vs rot{y_axis.upper()}(deg)")

    #Add lines connecting the points 
    fig.update_traces(mode='markers+lines')




    #Display the plot
    fig.show()


def main() -> None:
    data_to_display: str = input("Enter the rotations you would like to view(x/y): ")

    display_scatter_plot(data_to_display) 

if __name__ == "__main__":
    main() 